CREATE TABLE xt_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT uk_xt_roles_name UNIQUE (name)
);

CREATE INDEX idx_xt_roles_created_at ON xt_roles (created_at);
CREATE INDEX idx_xt_roles_updated_at ON xt_roles (updated_at);

CREATE TABLE xt_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_xt_users_role FOREIGN KEY (role_id) REFERENCES xt_roles(id),
    CONSTRAINT uk_xt_users_email UNIQUE (email)
);

CREATE INDEX idx_xt_users_email ON xt_users (email);
CREATE INDEX idx_xt_users_role_id ON xt_users (role_id);
CREATE INDEX idx_xt_users_created_at ON xt_users (created_at);
CREATE INDEX idx_xt_users_updated_at ON xt_users (updated_at);

INSERT INTO xt_roles (name) VALUES ('SUPER_ADMIN'), ('ADMIN'), ('TEAM_MEMBER');

CREATE TABLE oauth_clients (
    client_id VARCHAR(128) PRIMARY KEY,
    client_secret VARCHAR(256),
    client_name VARCHAR(256),
    grant_types VARCHAR(256),
    redirect_uris TEXT,
    scopes VARCHAR(256),
    access_token_validity INT,
    refresh_token_validity INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE oauth_authorization_codes (
    code VARCHAR(256) PRIMARY KEY,
    client_id VARCHAR(128),
    user_id UUID,
    redirect_uri TEXT,
    scopes VARCHAR(256),
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE oauth_access_tokens (
    token_id UUID PRIMARY KEY,
    client_id VARCHAR(128),
    user_id UUID,
    access_token TEXT,
    refresh_token TEXT,
    scopes VARCHAR(256),
    issued_at TIMESTAMP,
    expires_at TIMESTAMP,
    revoked BOOLEAN DEFAULT FALSE
);s

CREATE TABLE oauth_refresh_tokens (
    token_id UUID PRIMARY KEY,
    access_token_id UUID REFERENCES oauth_access_tokens(token_id),
    refresh_token TEXT,
    issued_at TIMESTAMP,
    expires_at TIMESTAMP,
    revoked BOOLEAN DEFAULT FALSE
);

