-- Create the user-role mapping table
CREATE TABLE xt_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_xa_user_role_user FOREIGN KEY (user_id) REFERENCES xt_users(id),
    CONSTRAINT fk_xa_user_role_role FOREIGN KEY (role_id) REFERENCES xt_roles(id),
    CONSTRAINT idx_xt_user_role_unique UNIQUE (user_id, role_id)
);

-- Add indexes to the new table
CREATE INDEX idx_xt_user_role_user_id ON xt_user_role (user_id);
CREATE INDEX idx_xt_user_role_role_id ON xt_user_role (role_id);
CREATE INDEX idx_xt_user_role_created_at ON xt_user_role (created_at);

-- Migrate existing data from xt_users.role_id to xt_user_role
INSERT INTO xt_user_role (user_id, role_id, created_at, updated_at)
SELECT id, role_id, COALESCE(created_at, CURRENT_TIMESTAMP), COALESCE(updated_at, CURRENT_TIMESTAMP)
FROM xt_users
WHERE role_id IS NOT NULL;

-- Drop the foreign key constraint from xt_users
ALTER TABLE xt_users DROP CONSTRAINT fk_xt_users_role;

-- Drop the index on the role_id column
DROP INDEX idx_xt_users_role_id;

-- Drop the role_id column from xt_users
ALTER TABLE xt_users DROP COLUMN role_id;
