-- schema.sql

-- Drop tables if they exist to ensure a clean state
DROP TABLE IF EXISTS xt_user_email_verification_history CASCADE;
DROP TABLE IF EXISTS xt_email_verification_batch CASCADE;
DROP TABLE IF EXISTS xt_users CASCADE;
DROP TABLE IF EXISTS integrated_app_key CASCADE;
DROP TABLE IF EXISTS integrations CASCADE;

-- Drop sequences if they exist
DROP SEQUENCE IF EXISTS xt_user_id_seq;
DROP SEQUENCE IF EXISTS xt_user_email_verification_history_id_seq;


-- Create sequences
CREATE SEQUENCE xt_user_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE xt_user_email_verification_history_id_seq START WITH 1 INCREMENT BY 1;

-- Create xt_users table
CREATE TABLE xt_users (
    id BIGINT NOT NULL,
    account_non_expired BOOLEAN NOT NULL,
    account_non_locked BOOLEAN NOT NULL,
    credentials_non_expired BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL,
    is_email_verified BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    external_id UUID NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL, -- Using VARCHAR for the enum
    PRIMARY KEY (id)
);

CREATE TABLE xt_email_verification_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    file_name VARCHAR(255),
    total_emails INT,
    processed_emails INT,
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (user_id) REFERENCES xt_users(id)
);

-- Create xt_user_email_verification_history table
CREATE TABLE xt_user_email_verification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    batch_id BIGINT,
    email VARCHAR(255),
    status VARCHAR(255),
    details TEXT,
    checked_at TIMESTAMP WITH TIME ZONE,
    source VARCHAR(255),
    ip_address VARCHAR(255),
    domain VARCHAR(255),
    recommendation VARCHAR(255),
    score INT,
    confidence VARCHAR(255),
    syntax_check BOOLEAN,
    mx_check BOOLEAN,
    disposable_check BOOLEAN,
    role_based_check BOOLEAN,
    blacklist_check BOOLEAN,
    catch_all_check BOOLEAN,
    smtp_check_status VARCHAR(255),
    smtp_ping_status VARCHAR(255),
    is_catch_all BOOLEAN,
    is_greylisted BOOLEAN,
    smtp_logs TEXT,
    FOREIGN KEY (user_id) REFERENCES xt_users(id),
    FOREIGN KEY (batch_id) REFERENCES xt_email_verification_batch(id)
);

-- Create integrated_app_key table with quoted column name
CREATE TABLE integrated_app_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_key VARCHAR(255),
    "value" VARCHAR(255) -- Quoted column name
);

-- Create integrations table with quoted column names
CREATE TABLE integrations (
    id BIGINT NOT NULL PRIMARY KEY,
    "key" VARCHAR(255), -- Quoted column name
    "value" VARCHAR(255) -- Quoted column name
);